// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/[locale]/category/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/category/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/category/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/search">> = Specific
  const handler = {} as typeof import("../../app/[locale]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/age-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/age-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/age-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/aspect-ratio-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/aspect-ratio-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/aspect-ratio-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/audio-bitrate-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/audio-bitrate-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/audio-bitrate-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/audio-cutter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/audio-cutter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/audio-cutter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/base64-encoder-decoder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/base64-encoder-decoder">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/base64-encoder-decoder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/bpm-tapper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/bpm-tapper">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/bpm-tapper/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/character-counter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/character-counter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/character-counter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/color-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/color-converter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/color-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/color-picker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/color-picker">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/color-picker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/compound-interest-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/compound-interest-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/compound-interest-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/css-gradient-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/css-gradient-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/css-gradient-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/csv-to-json/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/csv-to-json">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/csv-to-json/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/date-difference-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/date-difference-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/date-difference-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/discount-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/discount-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/discount-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/exif-remover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/exif-remover">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/exif-remover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/favicon-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/favicon-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/favicon-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/gpa-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/gpa-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/gpa-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/grade-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/grade-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/grade-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/hash-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/hash-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/hash-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/hashtag-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/hashtag-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/hashtag-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/html-entity-encoder-decoder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/html-entity-encoder-decoder">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/html-entity-encoder-decoder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/image-blur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/image-blur">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/image-blur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/image-color-picker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/image-color-picker">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/image-color-picker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/image-compressor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/image-compressor">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/image-compressor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/image-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/image-converter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/image-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/image-resizer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/image-resizer">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/image-resizer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/image-rotate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/image-rotate">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/image-rotate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/image-to-pdf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/image-to-pdf">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/image-to-pdf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/instagram-caption-spacer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/instagram-caption-spacer">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/instagram-caption-spacer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/ip-address-lookup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/ip-address-lookup">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/ip-address-lookup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/jpg-to-png/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/jpg-to-png">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/jpg-to-png/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/jpg-to-webp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/jpg-to-webp">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/jpg-to-webp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/json-diff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/json-diff">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/json-diff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/json-formatter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/json-formatter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/json-formatter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/json-to-csv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/json-to-csv">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/json-to-csv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/jwt-decoder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/jwt-decoder">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/jwt-decoder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/loan-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/loan-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/loan-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/lorem-ipsum-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/lorem-ipsum-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/lorem-ipsum-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/markdown-to-html/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/markdown-to-html">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/markdown-to-html/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/meta-tag-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/meta-tag-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/meta-tag-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/microphone-tester/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/microphone-tester">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/microphone-tester/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/multi-cropper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/multi-cropper">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/multi-cropper/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/open-graph-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/open-graph-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/open-graph-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/password-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/password-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/password-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/password-strength-checker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/password-strength-checker">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/password-strength-checker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/pdf-merger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/pdf-merger">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/pdf-merger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/pdf-to-image/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/pdf-to-image">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/pdf-to-image/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/percentage-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/percentage-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/percentage-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/png-to-jpg/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/png-to-jpg">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/png-to-jpg/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/pomodoro-timer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/pomodoro-timer">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/pomodoro-timer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/qr-code-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/qr-code-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/qr-code-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/random-password-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/random-password-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/random-password-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/robots-txt-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/robots-txt-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/robots-txt-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/roi-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/roi-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/roi-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/scientific-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/scientific-calculator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/scientific-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/screen-recorder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/screen-recorder">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/screen-recorder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/signature-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/signature-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/signature-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/sitemap-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/sitemap-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/sitemap-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/sql-formatter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/sql-formatter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/sql-formatter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/stopwatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/stopwatch">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/stopwatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/text-case-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/text-case-converter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/text-case-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/text-decorator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/text-decorator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/text-decorator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/text-diff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/text-diff">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/text-diff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/text-to-speech/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/text-to-speech">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/text-to-speech/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/todo-list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/todo-list">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/todo-list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/tweet-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/tweet-preview">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/tweet-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/twitter-card-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/twitter-card-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/twitter-card-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/unit-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/unit-converter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/unit-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/unix-timestamp-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/unix-timestamp-converter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/unix-timestamp-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/url-encoder-decoder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/url-encoder-decoder">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/url-encoder-decoder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/user-agent-parser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/user-agent-parser">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/user-agent-parser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/uuid-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/uuid-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/uuid-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/webcam-tester/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/webcam-tester">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/webcam-tester/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/webp-to-jpg/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/webp-to-jpg">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/webp-to-jpg/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/word-counter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/word-counter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/word-counter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/youtube-tag-extractor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/youtube-tag-extractor">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/youtube-tag-extractor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/youtube-thumbnail-downloader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/youtube-thumbnail-downloader">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/youtube-thumbnail-downloader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/tools/youtube-timestamp-link-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/youtube-timestamp-link-generator">> = Specific
  const handler = {} as typeof import("../../app/[locale]/tools/youtube-timestamp-link-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
