module.exports=[2441,a=>{"use strict";var b=a.i(79903);a.s(["Card",0,({children:a,padding:c="md",hover:d=!1,className:e="",onClick:f,...g})=>(0,b.jsx)("div",{className:`
        bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden
        ${{none:"",sm:"p-4",md:"p-6",lg:"p-8"}[c]}
        ${d?"hover:shadow-xl hover:border-transparent transition-all duration-300 cursor-pointer":""}
        ${e}
      `,onClick:f,...g,children:a})])},77089,a=>{"use strict";var b=a.i(79903),c=a.i(27585);a.s(["Button",0,({children:a,variant:d="primary",size:e="md",isLoading:f=!1,leftIcon:g,rightIcon:h,className:i="",disabled:j,href:k,locale:l,...m})=>{let n=`
    inline-flex items-center justify-center font-medium transition-all duration-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed
    ${{primary:"bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500 shadow-sm hover:shadow-md",secondary:"bg-white text-gray-700 border border-gray-300 hover:bg-gray-50 focus:ring-blue-500 shadow-sm",outline:"bg-transparent text-blue-600 border border-blue-600 hover:bg-blue-50 focus:ring-blue-500",ghost:"bg-transparent text-gray-600 hover:bg-gray-100 hover:text-gray-900 focus:ring-gray-500",danger:"bg-red-600 text-white hover:bg-red-700 focus:ring-red-500 shadow-sm hover:shadow-md"}[d]}
    ${{sm:"px-3 py-1.5 text-xs min-h-8",md:"px-4 py-2 text-sm min-h-10",lg:"px-6 py-3 text-base min-h-12"}[e]}
    ${i}
  `,o=(0,b.jsxs)(b.Fragment,{children:[f&&(0,b.jsxs)("svg",{className:"animate-spin -ml-1 mr-2 h-4 w-4 text-current",xmlns:"http://www.w3.org/2000/svg",fill:"none",viewBox:"0 0 24 24",children:[(0,b.jsx)("circle",{className:"opacity-25",cx:"12",cy:"12",r:"10",stroke:"currentColor",strokeWidth:"4"}),(0,b.jsx)("path",{className:"opacity-75",fill:"currentColor",d:"M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"})]}),!f&&g&&(0,b.jsx)("span",{className:"mr-2",children:g}),a,!f&&h&&(0,b.jsx)("span",{className:"ml-2",children:h})]});return k?(0,b.jsx)(c.Link,{href:k,locale:l,className:n,children:o}):(0,b.jsx)("button",{className:n,disabled:j||f,...m,children:o})}])},50088,a=>{"use strict";var b=a.i(79903),c=a.i(349),d=a.i(5931),e=a.i(77089),f=a.i(2441);function g({locale:a}){let g=(0,d.useTranslations)("Tools.url-encoder-decoder"),[h,i]=(0,c.useState)(""),[j,k]=(0,c.useState)(""),[l,m]=(0,c.useState)(""),[n,o]=(0,c.useState)(!1);return(0,b.jsxs)("div",{className:"space-y-6",children:[(0,b.jsxs)("div",{className:"grid grid-cols-1 md:grid-cols-2 gap-6",children:[(0,b.jsxs)(f.Card,{padding:"md",className:"space-y-4 h-full flex flex-col",children:[(0,b.jsx)("label",{className:"block text-sm font-medium text-gray-700",children:g("ui.input")}),(0,b.jsx)("textarea",{value:h,onChange:a=>i(a.target.value),className:"w-full flex-1 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none min-h-[200px]",placeholder:"https://example.com/search?q=hello world"}),(0,b.jsxs)("div",{className:"flex space-x-2 pt-2",children:[(0,b.jsx)(e.Button,{onClick:()=>{m("");try{k(encodeURIComponent(h))}catch(a){m(g("ui.error"))}},className:"flex-1",children:g("ui.encode")}),(0,b.jsx)(e.Button,{onClick:()=>{m("");try{k(decodeURIComponent(h))}catch(a){m(g("ui.error"))}},className:"flex-1",variant:"secondary",children:g("ui.decode")}),(0,b.jsx)(e.Button,{onClick:()=>{i(""),k(""),m("")},variant:"outline",children:g("ui.clear")})]})]}),(0,b.jsxs)(f.Card,{padding:"md",className:"space-y-4 h-full flex flex-col bg-gray-50",children:[(0,b.jsxs)("div",{className:"flex justify-between items-center",children:[(0,b.jsx)("label",{className:"block text-sm font-medium text-gray-700",children:g("ui.output")}),(0,b.jsx)(e.Button,{size:"sm",variant:"outline",onClick:()=>{j&&(navigator.clipboard.writeText(j),o(!0),setTimeout(()=>o(!1),2e3))},className:n?"text-green-600 border-green-600":"",children:n?g("ui.copied"):g("ui.copy")})]}),(0,b.jsx)("textarea",{readOnly:!0,value:j,className:`w-full flex-1 p-3 border rounded-md resize-none min-h-[200px] focus:outline-none ${l?"border-red-500 bg-red-50 text-red-700":"border-gray-300 bg-white"}`,placeholder:l||""}),l&&(0,b.jsx)("p",{className:"text-sm text-red-600",children:l})]})]}),(0,b.jsx)("div",{className:"text-center text-sm text-gray-500",children:g("ui.processingNote")})]})}a.s(["default",()=>g])}];

//# sourceMappingURL=Documents_MyGeminiProject_asset-tools-suite_app_1536bf2e._.js.map