module.exports=[2441,a=>{"use strict";var b=a.i(79903);a.s(["Card",0,({children:a,padding:c="md",hover:d=!1,className:e="",onClick:f,...g})=>(0,b.jsx)("div",{className:`
        bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden
        ${{none:"",sm:"p-4",md:"p-6",lg:"p-8"}[c]}
        ${d?"hover:shadow-xl hover:border-transparent transition-all duration-300 cursor-pointer":""}
        ${e}
      `,onClick:f,...g,children:a})])},77089,a=>{"use strict";var b=a.i(79903),c=a.i(27585);a.s(["Button",0,({children:a,variant:d="primary",size:e="md",isLoading:f=!1,leftIcon:g,rightIcon:h,className:i="",disabled:j,href:k,locale:l,...m})=>{let n=`
    inline-flex items-center justify-center font-medium transition-all duration-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed
    ${{primary:"bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500 shadow-sm hover:shadow-md",secondary:"bg-white text-gray-700 border border-gray-300 hover:bg-gray-50 focus:ring-blue-500 shadow-sm",outline:"bg-transparent text-blue-600 border border-blue-600 hover:bg-blue-50 focus:ring-blue-500",ghost:"bg-transparent text-gray-600 hover:bg-gray-100 hover:text-gray-900 focus:ring-gray-500",danger:"bg-red-600 text-white hover:bg-red-700 focus:ring-red-500 shadow-sm hover:shadow-md"}[d]}
    ${{sm:"px-3 py-1.5 text-xs min-h-8",md:"px-4 py-2 text-sm min-h-10",lg:"px-6 py-3 text-base min-h-12"}[e]}
    ${i}
  `,o=(0,b.jsxs)(b.Fragment,{children:[f&&(0,b.jsxs)("svg",{className:"animate-spin -ml-1 mr-2 h-4 w-4 text-current",xmlns:"http://www.w3.org/2000/svg",fill:"none",viewBox:"0 0 24 24",children:[(0,b.jsx)("circle",{className:"opacity-25",cx:"12",cy:"12",r:"10",stroke:"currentColor",strokeWidth:"4"}),(0,b.jsx)("path",{className:"opacity-75",fill:"currentColor",d:"M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"})]}),!f&&g&&(0,b.jsx)("span",{className:"mr-2",children:g}),a,!f&&h&&(0,b.jsx)("span",{className:"ml-2",children:h})]});return k?(0,b.jsx)(c.Link,{href:k,locale:l,className:n,children:o}):(0,b.jsx)("button",{className:n,disabled:j||f,...m,children:o})}])},88343,a=>{"use strict";var b=a.i(79903),c=a.i(349),d=a.i(5931),e=a.i(77089),f=a.i(2441);function g(){let a=(0,d.useTranslations)("Tools.bpm-tapper.ui"),[g,h]=(0,c.useState)([]),[i,j]=(0,c.useState)(null),[k,l]=(0,c.useState)(!1),m=(0,c.useCallback)(()=>{let a=Date.now();h(b=>{if(b.length>0&&a-b[b.length-1]>2e3)return[a];let c=[...b,a];return c.length>10?c.slice(c.length-10):c}),l(!0);let b=document.getElementById("tap-button");b&&(b.classList.add("scale-95"),setTimeout(()=>b.classList.remove("scale-95"),50))},[]);return(0,c.useEffect)(()=>{if(g.length>1){let a=[];for(let b=1;b<g.length;b++)a.push(g[b]-g[b-1]);j(6e4/(a.reduce((a,b)=>a+b,0)/a.length))}else j(null)},[g]),(0,c.useEffect)(()=>{let a=a=>{"Space"!==a.code||a.repeat||(a.preventDefault(),m())};return window.addEventListener("keydown",a),()=>window.removeEventListener("keydown",a)},[m]),(0,b.jsxs)("div",{className:"max-w-3xl mx-auto space-y-6",children:[(0,b.jsxs)(f.Card,{className:"p-8 text-center",children:[(0,b.jsxs)("div",{className:"mb-8",children:[(0,b.jsx)("div",{className:"text-6xl font-bold text-blue-600 mb-2 font-mono",children:i?i.toFixed(2):"--"}),(0,b.jsx)("div",{className:"text-gray-500 uppercase tracking-wider text-sm",children:a("bpm")}),i&&(0,b.jsxs)("div",{className:"mt-2 text-gray-400 text-sm",children:[a("nearestWhole"),": ",(0,b.jsx)("span",{className:"font-bold text-gray-600",children:Math.round(i)})]})]}),(0,b.jsxs)("button",{id:"tap-button",onClick:m,className:`
            w-64 h-64 rounded-full border-8 transition-all duration-100 focus:outline-none
            flex flex-col items-center justify-center mx-auto mb-8
            ${k?"border-blue-500 bg-blue-50 text-blue-600 shadow-lg scale-100":"border-gray-200 bg-gray-50 text-gray-400 hover:border-blue-300 hover:text-blue-400"}
          `,children:[(0,b.jsx)("span",{className:"text-2xl font-bold",children:a("tapHere")}),(0,b.jsx)("span",{className:"text-sm mt-2 opacity-70 px-4",children:a("tapInstruction")})]}),(0,b.jsxs)("div",{className:"flex justify-center items-center gap-8",children:[(0,b.jsxs)("div",{className:"text-gray-500",children:[a("count"),": ",(0,b.jsx)("span",{className:"font-bold text-gray-900",children:g.length})]}),(0,b.jsx)(e.Button,{onClick:()=>{h([]),j(null),l(!1)},variant:"outline",size:"sm",children:a("reset")})]})]}),(0,b.jsx)("div",{className:"text-center text-sm text-gray-500",children:a("processingNote")})]})}a.s(["default",()=>g])}];

//# sourceMappingURL=Documents_MyGeminiProject_asset-tools-suite_app_f1d421c1._.js.map